export interface StaticComment {
  id: string
  name: string
  role: string
  date: string
  message: string
  likes: number
}

export const staticComments: Record<string, StaticComment[]> = {
  "top-gen-ai-companies-usa-global-leaders": [
    {
      id: "1",
      name: "Priya Mehta",
      role: "AI Product Manager",
      date: "March 16, 2024",
      message: "Great breakdown! The comparison between OpenAI and Google DeepMind was especially insightful. Would love to see a follow-up on how these companies are approaching regulation.",
      likes: 24,
    },
    {
      id: "2",
      name: "Vipul Gupta",
      role: "ML Engineer",
      date: "March 17, 2024",
      message: "The point about infrastructure investment is spot-on. It's not just about research — you need massive compute to convert breakthroughs into real products.",
      likes: 18,
    },
    {
      id: "3",
      name: "Aditi Saxena",
      role: "Tech Journalist",
      date: "March 18, 2024",
      message: "Really appreciated the global perspective here. China's AI ecosystem is often underreported in Western media, so it was refreshing to see it acknowledged.",
      likes: 31,
    },
  ],
  "generative-ai-crucial-digital-transformation-2024": [
    {
      id: "1",
      name: "Dev Patel",
      role: "CTO at FinEdge",
      date: "March 15, 2024",
      message: "The 30–50% developer productivity stat really jumped out at me. We've seen similar numbers in our own teams since rolling out AI coding assistants. The ROI is real.",
      likes: 42,
    },
    {
      id: "2",
      name: "Shreya Ghosh",
      role: "Digital Strategy Lead",
      date: "March 16, 2024",
      message: "Excellent article. One thing I'd add — change management is the biggest blocker for Gen AI adoption, not technology readiness. The people side is harder than the tech side.",
      likes: 29,
    },
  ],
  "future-machine-learning-trends": [
    {
      id: "1",
      name: "Simran Kaur",
      role: "Data Scientist",
      date: "March 14, 2024",
      message: "The section on foundation models really resonated. We've almost completely stopped training from scratch. Fine-tuning is the new default and it's saving us months of work.",
      likes: 37,
    },
    {
      id: "2",
      name: "Rajat Jain",
      role: "ML Ops Engineer",
      date: "March 15, 2024",
      message: "Love the focus on MLOps maturity. The gap between research and production ML is still enormous in most orgs. This deserves its own article honestly.",
      likes: 22,
    },
    {
      id: "3",
      name: "Kriti Sinha",
      role: "Research Scientist",
      date: "March 16, 2024",
      message: "Multimodal learning is the one I'm most excited about. Once you can reason across text, images, and audio together, entirely new applications become possible.",
      likes: 45,
    },
  ],
  "ai-ethics-building-responsible-ai-systems": [
    {
      id: "1",
      name: "Payal Chatterjee",
      role: "AI Ethics Researcher",
      date: "March 13, 2024",
      message: "Thorough and balanced. I especially appreciated the framing around governance structures. Ethics without accountability mechanisms is just good intentions.",
      likes: 58,
    },
    {
      id: "2",
      name: "Ankit Srivastava",
      role: "Legal Counsel, Tech Sector",
      date: "March 14, 2024",
      message: "From a regulatory standpoint, explainability is no longer optional in many jurisdictions. Companies that haven't invested in XAI are going to face compliance pain soon.",
      likes: 34,
    },
  ],
  "what-is-generative-ai-changing-communication": [
    {
      id: "1",
      name: "Ritu Pandey",
      role: "Communications Strategist",
      date: "March 12, 2024",
      message: "The point about AI amplifying rather than replacing human creativity is key. The best results I've seen always involve a human in the loop guiding the AI.",
      likes: 41,
    },
    {
      id: "2",
      name: "Arjun Nair",
      role: "Content Director",
      date: "March 13, 2024",
      message: "Loved the accessibility angle. Text-to-speech and captioning improvements driven by gen AI are genuinely life-changing for millions of people.",
      likes: 27,
    },
    {
      id: "3",
      name: "Sakshi Mishra",
      role: "Brand Strategist",
      date: "March 14, 2024",
      message: "We've gone from producing 10 pieces of content a week to 50+ with the same team. The productivity gains are incredible but the quality bar matters more than ever.",
      likes: 33,
    },
  ],
  "nlp-breaking-language-barriers": [
    {
      id: "1",
      name: "Komal Bhatia",
      role: "Computational Linguist",
      date: "March 11, 2024",
      message: "The jump in translation quality post-transformer is genuinely remarkable. Low-resource language pairs have improved the most, which has huge humanitarian implications.",
      likes: 39,
    },
    {
      id: "2",
      name: "Mohit Yadav",
      role: "Product Manager",
      date: "March 12, 2024",
      message: "Sentiment analysis has been a game-changer for our customer feedback pipeline. What used to take weeks of manual tagging now runs overnight.",
      likes: 21,
    },
  ],
  "computer-vision-applications-modern-business": [
    {
      id: "1",
      name: "Nikhil Bansal",
      role: "Manufacturing Engineer",
      date: "March 10, 2024",
      message: "The quality inspection use case is incredibly real. We deployed a vision system last year and defect detection accuracy went from 94% to 99.2%. The difference is huge at scale.",
      likes: 52,
    },
    {
      id: "2",
      name: "Alok Tripathi",
      role: "Retail Technology Lead",
      date: "March 11, 2024",
      message: "Cashier-less stores are fascinating but the real win in retail CV for us has been inventory tracking. Knowing what's on shelves in real time changes everything about replenishment.",
      likes: 28,
    },
  ],
  "deep-learning-fundamentals-beginners-guide": [
    {
      id: "1",
      name: "Deepak Chauhan",
      role: "Computer Science Student",
      date: "March 9, 2024",
      message: "This is the clearest explanation of backpropagation I've read outside of a textbook. Bookmarking this to share with my study group.",
      likes: 67,
    },
    {
      id: "2",
      name: "Saurabh Thakur",
      role: "Software Developer",
      date: "March 10, 2024",
      message: "I've been wanting to get into ML for a while and kept bouncing off dense academic resources. This is exactly the right level of depth to get started. Thank you!",
      likes: 44,
    },
    {
      id: "3",
      name: "Abhishek Dubey",
      role: "Data Analyst",
      date: "March 11, 2024",
      message: "The frameworks section was super helpful. PyTorch vs TensorFlow deserves its own full article though — the choice really matters depending on your use case.",
      likes: 19,
    },
  ],
  "robotics-ai-perfect-partnership": [
    {
      id: "1",
      name: "Nisha Purohit",
      role: "Robotics Engineer",
      date: "March 8, 2024",
      message: "Finally an article that doesn't hype autonomous robots as ready for everything. The sim-to-real gap is still a massive challenge. Great nuanced take.",
      likes: 36,
    },
    {
      id: "2",
      name: "Ishaan Khanna",
      role: "Operations Director",
      date: "March 9, 2024",
      message: "The warehouse and logistics section describes our world perfectly. AMRs have cut our picking time by 40% and reduced injuries significantly. The ROI came in under 18 months.",
      likes: 49,
    },
  ],
  "ai-healthcare-revolutionizing-patient-care": [
    {
      id: "1",
      name: "Varun Aggarwal",
      role: "Radiologist",
      date: "March 7, 2024",
      message: "As a radiologist, I see AI as an invaluable second opinion, not a replacement. The studies showing parity with specialists are compelling, but clinical context still matters enormously.",
      likes: 73,
    },
    {
      id: "2",
      name: "Tanvi Kulkarni",
      role: "Healthcare Administrator",
      date: "March 8, 2024",
      message: "The administrative automation piece is often overlooked. We've reduced prior auth turnaround from 5 days to 4 hours. That directly impacts patient care timelines.",
      likes: 55,
    },
    {
      id: "3",
      name: "Jatin Oberoi",
      role: "Clinical Informatics Specialist",
      date: "March 9, 2024",
      message: "Equity in healthcare AI is the issue I think about most. If these systems are trained on non-representative data, they'll systematically underserve vulnerable populations.",
      likes: 61,
    },
  ],
  "reinforcement-learning-training-ai-through-experience": [
    {
      id: "1",
      name: "Nandini Rao",
      role: "AI Researcher",
      date: "March 6, 2024",
      message: "The AlphaGo moment was a real inflection point for public awareness of AI capability. What's interesting is that AlphaZero's pure self-play approach was arguably even more remarkable.",
      likes: 43,
    },
    {
      id: "2",
      name: "Rakesh Solanki",
      role: "Quant Analyst",
      date: "March 7, 2024",
      message: "RL in recommendation systems is something I wish more people understood. The reward functions you choose have enormous downstream effects on user behavior and engagement.",
      likes: 31,
    },
  ],
  "edge-ai-bringing-intelligence-to-devices": [
    {
      id: "1",
      name: "Umesh Pawar",
      role: "Embedded Systems Engineer",
      date: "March 5, 2024",
      message: "The hardware section is really timely. The new NPU architectures are incredible — we're running models on micro-controllers that would have required a cloud VM 3 years ago.",
      likes: 38,
    },
    {
      id: "2",
      name: "Yash Bhardwaj",
      role: "IoT Solutions Architect",
      date: "March 6, 2024",
      message: "Privacy is the killer feature for edge AI that businesses often don't emphasize enough. In healthcare and finance especially, on-device inference is a regulatory advantage.",
      likes: 29,
    },
  ],
  "ai-finance-transforming-banking-investment": [
    {
      id: "1",
      name: "Hitesh Parmar",
      role: "Head of Risk, Regional Bank",
      date: "March 4, 2024",
      message: "The fraud detection numbers in this article align with what I've seen in practice. The reduction in false positives alone has saved enormous goodwill with customers.",
      likes: 47,
    },
    {
      id: "2",
      name: "Jyoti Khandelwal",
      role: "FinTech Product Lead",
      date: "March 5, 2024",
      message: "Robo-advisors are a fascinating space. The real disruption won't be replacing advisors — it's making sophisticated financial planning accessible to people who could never afford it before.",
      likes: 34,
    },
    {
      id: "3",
      name: "Keshav Tandon",
      role: "Compliance Officer",
      date: "March 6, 2024",
      message: "The regulatory compliance section deserves more depth. KYC automation has come a long way but explainability requirements from regulators are still a real challenge for most models.",
      likes: 22,
    },
  ],
}
